services:
  nodecg:
    container_name: nodecg
    # image: na2na/nodecg-usual:${{ github.ref }}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # volumes: # cfgとかはvolumeにしたほうが良さそう
    #   - .config:/app/.config
    ports:
      - "9090:9090"
