services:
  nodecg:
    container_name: nodecg
    # image: na2na/2na2-discord:main
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # volumes: # cfgとかはvolumeにしたほうが良さそう
    #   - .config:/app/.config
    ports:
      - "9090:9090"
