name: CI
on: push
jobs:
  ESLint-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: ci
        run: yarn install:ci
      - name: ESLint
        run: yarn lint:dashboard
  ESLint-graphics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: ci
        run: yarn install:ci
      - name: ESLint
        run: yarn lint:graphics
  ESLint-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: ci
        run: yarn install:ci
      - name: ESLint
        run: yarn lint:extension
  tscNoEmit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: ci
        run: yarn install:ci
      - name: tscNoEmit
        run: yarn tscNoEmit
