name: CI
on: push
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: ci
        run: yarn install:ci
      - name: ESLint
        run: yarn lint
  tscNoEmit:
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: settingUp packages
        run: npm install --global nodecg-cli
      - name: ci
        run: mkdir nodecg && cd nodecg && nodecg setup && nodecg install na2na-p/my-usual-layout && cd nodecg/bundles/my-usual-layout && yarn install
      - name: tscNoEmit
        run: cd nodecg/bundles/my-usual-layout && yarn tscNoEmit
