name: Enable auto merge
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
    branches:
      - main
      - develop

jobs:
  enable-auto-merge:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
        env:
          OPENSSL_CONF: /dev/null
      - uses: alexwilson/enable-github-automerge-action@main
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
