name: LicenseCheck
on:
  push:
    branches:
      - develop
    paths:
      - yarn.lock
      - dashboard/yarn.lock
      - graphics/yarn.lock
      - extension/yarn.lock
  pull_request:

jobs:
  License-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: ci
        run: yarn install:ci
      - name: License Check
        run: yarn licenseCheck
